AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'test/**/*.rb'
    - '**/*.rake'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'bin/**/*'
    - 'Rakefile'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'client/node_modules/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

ClassAndModuleChildren:
  EnforcedStyle: nested

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets


Metrics/AbcSize:
  Max: 25

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/ClassAndModuleChildren:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    "%i": ()
    "%w": ()

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/MethodLength:
  CountComments: false
  Max: 15
  Exclude:
    - "spec/**/*.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
    - "config/initializers/rails_admin.rb"

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
